Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CourseOPR.Database;
using CourseOPR.Models;

namespace CourseOPR.Controllers
{
    public class GroupsController : Controller
    {
        private readonly ApplicationContext _context;

        public GroupsController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {
            var applicationContext = _context.Group.Include( m=> m.Speciality);
            return View(await applicationContext.ToListAsync());
        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Group == null)
            {
                return NotFound();
            }

            var group = await _context.Group
                .Include(m =>m.Speciality)
                .FirstOrDefaultAsync(m => m.GroupId == id);
            if (group == null)
            {
                return NotFound();
            }

            return View(group);
        }

        // GET: Groups/Create
        public IActionResult Create()
        {
            ViewData["SpecialityId"] = new SelectList(_context.Speciality, "SpecialityId", "SpecialityName");
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GroupId,GroupNumber,SpecialityId")] Group group)
        {
            if (ModelState.IsValid)
            {
                _context.Add(group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SpecialityId"] = new SelectList(_context.Speciality, "SpecialityId", "SpecialityId", group.SpecialityId);
            return View(group);
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Group == null)
            {
                return NotFound();
            }

            var group = await _context.Group.FindAsync(id);
            if (group == null)
            {
                return NotFound();
            }
            Speciality speciality = await _context.Speciality.FirstOrDefaultAsync(s => s.SpecialityId == group.SpecialityId);
            group.Speciality = speciality;
            group.SpecialityId = speciality.SpecialityId;
            ViewData["SpecialityId"] = new SelectList(_context.Speciality, "SpecialityId", "SpecialityName", group.SpecialityId);
            return View(group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GroupId,GroupNumber,SpecialityId")] Group group)
        {
            if (id != group.GroupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(group.GroupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SpecialityId"] = new SelectList(_context.Speciality, "SpecialityId", "SpecialityId", group.SpecialityId);
            return View(group);
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Group == null)
            {
                return NotFound();
            }

            var group = await _context.Group
                .Include(m => m.Speciality)
                .FirstOrDefaultAsync(m => m.GroupId == id);
            if (group == null)
            {
                return NotFound();
            }

            return View(group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Group == null)
            {
                return Problem("Entity set 'ApplicationContext.Group'  is null.");
            }
            var group = await _context.Group.FindAsync(id);
            if (group != null)
            {
                _context.Group.Remove(group);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GroupExists(int id)
        {
          return (_context.Group?.Any(e => e.GroupId == id)).GetValueOrDefault();
        }
    }
}

Controllers/ScoresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CourseOPR.Database;
using CourseOPR.Models;
using Microsoft.AspNetCore.Authorization;
using CourseOPR.Servises;
using static System.Formats.Asn1.AsnWriter;
using iText.Kernel.Pdf.Annot;

namespace CourseOPR.Controllers
{
    [Authorize]
    public class ScoresController : Controller
    {
        private readonly ApplicationContext _context;
        public Parser parser= new Parser();
        string path = "D:\\C#\\text.txt";
        public PdfCreator pdfCreator= new PdfCreator();

        public ScoresController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Scores
        public async Task<IActionResult> Index()
        {
            
            var applicationContext = _context.Score.Include(s => s.Student).Include(s => s.Subject);
            return View(await applicationContext.ToListAsync());
        }


        public  IActionResult SelectStudent()
        {
            ViewData["StudentId"] = new SelectList(_context.Student, "StudentId", "StudentFullName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async  Task<IActionResult> SelectStudent([Bind("StudentId,StudentFullName")] Student student)
        {
            var studentId = student.StudentId;
            return Redirect("ViewScoreStudent/" + studentId.ToString());
        }

        public async Task<IActionResult> ViewScoreStudent(int? id)
        {
            if (id == null || _context.Score == null)
            {
                return NotFound();
            }
            var student = await _context.Student.FirstOrDefaultAsync(c=>c.StudentId==id);
            var score = _context.Score.Where(u => u.StudentId == student.StudentId).Include(s=>s.Student)
                .Include(s=>s.Subject);
            if (score == null)
            {
                return NotFound();
            }
            return View(score);

        }

        public async Task<IActionResult> GeneratePdf(int? id)
        {
            if (id == null || _context.Score == null)
            {
                return NotFound();
            }
            var student = await _context.Student.FirstOrDefaultAsync(c => c.StudentId == id);
            var score = _context.Score.Where(u => u.StudentId == student.StudentId).Include(s => s.Student)
                .Include(s => s.Subject).ToList();
            if (score == null)
            {
                return NotFound();
            }
            var result = pdfCreator.CreatePdf(score);
            return File(result, "application/pdf", "DownloadName.pdf");
        }


        // GET: Scores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Score == null)
            {
                return NotFound();
            }

            var score = await _context.Score
                .Include(s => s.Student)
                .Include(s => s.Subject)
                .FirstOrDefaultAsync(m => m.ScoreId == id);
            if (score == null)
            {
                return NotFound();
            }

            return View(score);
        }

        // GET: Scores/Create
        public IActionResult Create()
        {
            ViewData["StudentId"] = new SelectList(_context.Student, "StudentId", "StudentFullName");
            ViewData["SubjectId"] = new SelectList(_context.Subject, "SubjectId", "SubjectName");
            return View();
        }


        public IActionResult Parse()
        {
            ViewData["StudentId"] = new SelectList(_context.Student, "StudentId", "StudentFullName");
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Parse([Bind("ScoreId,ScoreValue,StudentId,SubjectId")] Score score) 
        {
            //var speciality = _context.Speciality(x => x.Speciality)
            //    .Include(c => c.Student)
            //    .Include(c => c.Subject).ToList();


            var student = await _context.Student.FirstOrDefaultAsync(s => s.StudentId == score.StudentId);
            var group = await _context.Group.FirstOrDefaultAsync(c=>c.GroupId==student.GroupId);
            var subject = _context.Subject.Where(c=>c.SpecialityId==group.SpecialityId).ToList();

            var parseScore = parser.ArrayParse(path);
            for (int i=0;i<subject.Count();i++)
            {
                score.ScoreId = 0;
                score.SubjectId = subject[i].SubjectId;
                score.ScoreValue = parseScore[i].ToString();
                _context.Add(score);
                await _context.SaveChangesAsync();
            }        
            score.Student= student;
            score.StudentId = student.StudentId;
            ViewData["StudentId"] = new SelectList(_context.Student, "StudentId", "StudentFullName", score.StudentId);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }


        // POST: Scores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ScoreId,ScoreValue,StudentId,SubjectId")] Score score)
        {
            if (ModelState.IsValid)
            {
                _context.Add(score);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StudentId"] = new SelectList(_context.Student, "StudentId", "StudentId", score.StudentId);
            ViewData["SubjectId"] = new SelectList(_context.Subject, "SubjectId", "SubjectId", score.SubjectId);
            return View(score);
        }

        // GET: Scores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Score == null)
            {
                return NotFound();
            }

            var score = await _context.Score.FindAsync(id);
            if (score == null)
            {
                return NotFound();
            }
            ViewData["StudentId"] = new SelectList(_context.Student, "StudentId", "StudentFullName", score.StudentId);
            ViewData["SubjectId"] = new SelectList(_context.Subject, "SubjectId", "SubjectName", score.SubjectId);
            return View(score);
        }

        // POST: Scores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ScoreId,ScoreValue,StudentId,SubjectId")] Score score)
        {
            if (id != score.ScoreId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(score);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScoreExists(score.ScoreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StudentId"] = new SelectList(_context.Student, "StudentId", "StudentId", score.StudentId);
            ViewData["SubjectId"] = new SelectList(_context.Subject, "SubjectId", "SubjectId", score.SubjectId);
            return View(score);
        }

        // GET: Scores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Score == null)
            {
                return NotFound();
            }

            var score = await _context.Score
                .Include(s => s.Student)
                .Include(s => s.Subject)
                .FirstOrDefaultAsync(m => m.ScoreId == id);
            if (score == null)
            {
                return NotFound();
            }

            return View(score);
        }

        // POST: Scores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Score == null)
            {
                return Problem("Entity set 'ApplicationContext.Score'  is null.");
            }
            var score = await _context.Score.FindAsync(id);
            if (score != null)
            {
                _context.Score.Remove(score);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ScoreExists(int id)
        {
          return (_context.Score?.Any(e => e.ScoreId == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CourseOPR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CourseOPR.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Scores" asp-action="Index">Главная</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculties" asp-action="Index">Факультеты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Specialities" asp-action="Index">Специальности</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Groups" asp-action="Index">Группы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Студенты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subjects" asp-action="Index">Предметы</a>
                        </li>


                    </ul>
                </div>
                <div align="right">
                    <ul class="nav flex-grow-1">
                         <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <div align="right">    
                                    <a>@User.Identity.Name</a>
                                     <a>
                                         <form method="post" asp-controller="Account" asp-action="Logout">
                                         <input type="submit" value="Выход" />
                                        </form>
                                    </a>

                                </div>
                            }
                            else
                            {
                                <a asp-controller="Account" asp-action="Login">Вход</a>
                                <a asp-controller="Account" asp-action="Register">Регистрация</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CourseOPR - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>